name: tmux-armhf
version: 2.3
summary: tmux is a terminal multiplexer (non-official)
description: |
 it enables a number of terminals (or windows), each running a separate program,
 to be created, accessed, and controlled from a single screen. tmux may be
 detached from a screen and continue running in the background, then later
 reattached.

grade: devel
confinement: devmode

apps:
  tmux:
    command: bin/tmux

parts:
  tmux:
    plugin: x-autotools
    configflags:
      - --host=x86_64-unknown-linux-gnu
    source: https://github.com/tmux/tmux.git
    source-type: git
    source-tag: '2.4'
    stage-packages:
      - libevent-2.0-5:armhf
      - libncurses5:armhf
